### ISSUE TITLE
Version 3.0.0 Cargo build error out of the box

### ISSUE THREAD

**Issue by CaptainIsaaca** [HristoGochevPersonal/merkle_hash#21]
When upgraded the version to 3.0.0 cargo failed to build throwing internal error as follows: 
 --> `C:\Users\Name\\.cargo\registry\src\github.com-1ecc6299db9ec823\merkle_hash-3.0.0\src\merkle_node.rs:62:21`

62 |                     let Ok(absolute_path) = Utf8PathBuf::from_path_buf(entry?.path())else{
63 |                          bail!("Path is not valid UTF8 path")
64 |                    };
   | |______________________^
   |
= note: see issue #87335 <https://github.com/rust-lang/rust/issues/87335> for more information

Environment: 
OS: Windows
Rust Version: rustc 1.64.0 (a55dd71d5 2022-09-19) (system)
Cargo rust version: `rust-version = "1.57"`

**Comment by hristogochev** [comment]
Are you using Rust 1.65.0?

**Comment by CaptainIsaaca** [comment]
> Are you using Rust 1.65.0?

Nope. 1.57 (updated in issue body). Rust version is required by the Tauri framework, bumping it up somehow breaks dependencies.

**Comment by hristogochev** [comment]
Removed the use of the let-else feature in [741a42](https://github.com/hristo-gochev/merkle_hash/commit/741a4254abe900a3679d5aaf1d7129c5019366ba). 
Can you check if it builds for you now using the newest version (3.0.1)?

**Comment by CaptainIsaaca** [comment]
Yes, magically solved my issue. Even no need to bump the version it fetched the new batch automatically. 
Thanks for the fix. Great module IMO.

**Comment by CaptainIsaaca** [comment]
Yes, magically solved my issue. Even no need to bump the version it fetched the new batch automatically.
Thanks for the fix. Great module IMO.
